site_name: Сайт-портфолио

nav:
  - Главная: index.md
  - Об авторе: about.md

theme:
  name: material
  palette:
    - scheme: slate
      primary: pink
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Светлая тема
    - scheme: default
      primary: pink
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Темная тема

  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate

  hide:
    - navigation

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences