site_name: Сайт-портфолио|Анастасия Данилова

nav:
  - Главная: index.md
  - Об авторе: about.md
  - Лабораторные работы:
    - Обзор: labs/index.md
    - Лабораторная работа №1: labs/lab1.md
  - Контакты: contact.md
theme:
  name: material
  favicon: assets/images/icon.png
  logo: assets/images/logo.png
  palette:
    - scheme: slate
      primary: pink
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Светлая тема
    - scheme: default
      primary: pink
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Темная тема

  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate

  hide:
    - navigation

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences